/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Environments */
        get: operations["list_environments_api_environments_get"];
        put?: never;
        /** Upload Environment */
        post: operations["upload_environment_api_environments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{environment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Environment */
        get: operations["get_environment_api_environments__environment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fleet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fleet */
        get: operations["get_fleet_api_fleet_get"];
        put?: never;
        /** Upload Fleet */
        post: operations["upload_fleet_api_fleet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fleet/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fleet Models */
        get: operations["get_fleet_models_api_fleet_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plan Jobs */
        get: operations["list_plan_jobs_api_plan_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan Job */
        get: operations["get_plan_job_api_plan_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan-jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Plan Job
         * @description Отмена расчета. Идемпотентна: отмена завершенной работы — не ошибка,
         *     оператор мог нажать кнопку ровно в момент завершения.
         */
        post: operations["cancel_plan_job_api_plan_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_api_plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Plan
         * @description ЭКС.ФТ.6 «Подтвердить». 409 при конфликте — с именем подтвердившего.
         */
        post: operations["confirm_plan_api_plans__plan_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Plan
         * @description ЭКС.ФТ.7-8: файл по одному БВС (или сводный по группе).
         */
        get: operations["export_plan_api_plans__plan_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/export/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Plan Archive
         * @description ЭКС.ФТ.7 «Скачать все» — архив с KML и GeoJSON по каждому БВС группы.
         */
        get: operations["export_plan_archive_api_plans__plan_id__export_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/safety-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Safety Check */
        post: operations["run_safety_check_api_safety_checks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/safety-checks/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Safety Check */
        get: operations["get_latest_safety_check_api_safety_checks_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/safety-checks/recheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recheck Safety Check
         * @description БЕЗ.ФТ.6 «Повторить проверку» — без автоматического пересчета.
         */
        post: operations["recheck_safety_check_api_safety_checks_recheck_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_tasks__task_id__get"];
        /** Update Task */
        put: operations["update_task_api_tasks__task_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_plan_api_plans_post */
        Body_create_plan_api_plans_post: {
            /** Task Id */
            task_id: string;
            /** Wait S */
            wait_s?: number | null;
        };
        /** Body_create_task_api_tasks_post */
        Body_create_task_api_tasks_post: {
            /** Area File */
            area_file: string;
            /** Cloud Cover Pct */
            cloud_cover_pct?: number | null;
            /** Criterion Alpha */
            criterion_alpha?: number | null;
            /** Criterion Mode */
            criterion_mode: string;
            /** Environment Id */
            environment_id: string;
            /** Gsd Cm */
            gsd_cm: number;
            /** Name */
            name: string;
            /** Survey Type */
            survey_type: string;
            /** Wind Speed Ms */
            wind_speed_ms?: number | null;
            /** Window End */
            window_end?: string | null;
            /** Window Start */
            window_start?: string | null;
            /**
             * Work Date
             * Format: date
             */
            work_date: string;
        };
        /** Body_recheck_safety_check_api_safety_checks_recheck_post */
        Body_recheck_safety_check_api_safety_checks_recheck_post: {
            /** Plan Id */
            plan_id: string;
        };
        /** Body_run_safety_check_api_safety_checks_post */
        Body_run_safety_check_api_safety_checks_post: {
            /** Plan Id */
            plan_id: string;
            /** Wait S */
            wait_s?: number | null;
        };
        /** Body_update_task_api_tasks__task_id__put */
        Body_update_task_api_tasks__task_id__put: {
            /** Area File */
            area_file: string;
            /** Cloud Cover Pct */
            cloud_cover_pct?: number | null;
            /** Criterion Alpha */
            criterion_alpha?: number | null;
            /** Criterion Mode */
            criterion_mode: string;
            /** Expected Version */
            expected_version: number;
            /** Gsd Cm */
            gsd_cm: number;
            /** Name */
            name: string;
            /** Survey Type */
            survey_type: string;
            /** Wind Speed Ms */
            wind_speed_ms?: number | null;
            /** Window End */
            window_end?: string | null;
            /** Window Start */
            window_start?: string | null;
            /**
             * Work Date
             * Format: date
             */
            work_date: string;
        };
        /** Body_upload_environment_api_environments_post */
        Body_upload_environment_api_environments_post: {
            /** File */
            file: string;
            /** Name */
            name: string;
        };
        /** Body_upload_fleet_api_fleet_post */
        Body_upload_fleet_api_fleet_post: {
            /** File */
            file: string;
        };
        /** EnvironmentDetail */
        EnvironmentDetail: {
            counts: components["schemas"]["LayerCounts"];
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["ValidationIssue"][];
            /** Id */
            id: string;
            /** Layers */
            layers: {
                [key: string]: {
                    [key: string]: unknown;
                }[];
            };
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "Корректна" | "Содержит ошибки";
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** EnvironmentSummary */
        EnvironmentSummary: {
            counts: components["schemas"]["LayerCounts"];
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["ValidationIssue"][];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "Корректна" | "Содержит ошибки";
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** FleetDetail */
        FleetDetail: {
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["FleetIssue"][];
            /** Id */
            id: string;
            /** Instances */
            instances: components["schemas"]["FleetInstance"][];
            /** Ready Count */
            ready_count: number;
            /**
             * Status
             * @enum {string}
             */
            status: "Корректна" | "Содержит ошибки";
            /** Total */
            total: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** FleetInstance */
        FleetInstance: {
            /** Base Launch Site */
            base_launch_site?: string | null;
            /** Error */
            error?: string | null;
            /** Inventory Number */
            inventory_number: string;
            /** Model Key */
            model_key: string;
            /** Model Name */
            model_name: string;
            /** Status */
            status: string;
            /** Valid */
            valid: boolean;
        };
        /** FleetIssue */
        FleetIssue: {
            /** Inventory Number */
            inventory_number?: string | null;
            /** Message */
            message: string;
        };
        /** FleetSummary */
        FleetSummary: {
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["FleetIssue"][];
            /** Id */
            id: string;
            /** Ready Count */
            ready_count: number;
            /**
             * Status
             * @enum {string}
             */
            status: "Корректна" | "Содержит ошибки";
            /** Total */
            total: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobInfo */
        JobInfo: {
            /**
             * Auto Recalc Count
             * @default 0
             */
            auto_recalc_count: number;
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
            /** Error */
            error?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Plan Id */
            plan_id?: string | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Queued At
             * Format: date-time
             */
            queued_at: string;
            /** Result Plan Id */
            result_plan_id?: string | null;
            /** Result Report Id */
            result_report_id?: string | null;
            /** Stage */
            stage?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
            /** Task Id */
            task_id: string;
        };
        /** LayerCounts */
        LayerCounts: {
            /**
             * Airspace
             * @default 0
             */
            airspace: number;
            /**
             * Launch Site
             * @default 0
             */
            launch_site: number;
            /**
             * No Fly
             * @default 0
             */
            no_fly: number;
            /**
             * Obstacle
             * @default 0
             */
            obstacle: number;
            /**
             * Reserve Site
             * @default 0
             */
            reserve_site: number;
        };
        /** ModelSpecOut */
        ModelSpecOut: {
            /** Comm Range Km */
            comm_range_km: number;
            /** Compatible Cameras */
            compatible_cameras: string[];
            /** Height Max M */
            height_max_m: number | null;
            /** Height Min M */
            height_min_m: number;
            /** Key */
            key: string;
            /** Max Flight Time Min */
            max_flight_time_min: number;
            /** Max Route Km */
            max_route_km: number | null;
            /** Max Wind Ms */
            max_wind_ms: number;
            /** Name */
            name: string;
            /** Speed Max Ms */
            speed_max_ms: number;
            /** Speed Min Ms */
            speed_min_ms: number;
            /** Uav Type */
            uav_type: string;
        };
        /** PlanDetail */
        PlanDetail: {
            /** Budget S */
            budget_s: number;
            /** Camera Key */
            camera_key: string;
            /** Confirmed At */
            confirmed_at?: string | null;
            /** Confirmed By */
            confirmed_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Criterion Alpha */
            criterion_alpha: number;
            /** Criterion Mode */
            criterion_mode: string;
            /** Cruise Speed Mps */
            cruise_speed_mps: number;
            /** Exported At */
            exported_at?: string | null;
            /** Height M */
            height_m: number;
            /** Id */
            id: string;
            /** Is Optimal */
            is_optimal: boolean;
            /** J1 S */
            j1_s: number;
            /** J2 S */
            j2_s: number;
            /** Model Key */
            model_key: string;
            /** Sortie Count */
            sortie_count: number;
            /** Sorties */
            sorties: components["schemas"]["PlanSortie"][];
            /**
             * Status
             * @default Черновик
             */
            status: string;
            /** Swath M */
            swath_m: number;
            /** Task Id */
            task_id: string;
            /** Uav Model */
            uav_model: string;
            /** Version */
            version: number;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** PlanSortie */
        PlanSortie: {
            /** Distance M */
            distance_m: number;
            /**
             * End Utc
             * Format: date-time
             */
            end_utc: string;
            /** Flight Time S */
            flight_time_s: number;
            /** Landing Site */
            landing_site?: string | null;
            /** Sortie Index */
            sortie_index: number;
            /**
             * Start Utc
             * Format: date-time
             */
            start_utc: string;
            /** Survey Tracks Geojson */
            survey_tracks_geojson: {
                [key: string]: unknown;
            };
            /** Takeoff Site */
            takeoff_site?: string | null;
            /** Track Geojson */
            track_geojson: {
                [key: string]: unknown;
            };
            /** Uav Id */
            uav_id: string;
        };
        /** PlanSummary */
        PlanSummary: {
            /** Confirmed At */
            confirmed_at?: string | null;
            /** Confirmed By */
            confirmed_by?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Criterion Alpha */
            criterion_alpha: number;
            /** Criterion Mode */
            criterion_mode: string;
            /** Exported At */
            exported_at?: string | null;
            /** Id */
            id: string;
            /** Is Optimal */
            is_optimal: boolean;
            /** J1 S */
            j1_s: number;
            /** J2 S */
            j2_s: number;
            /** Sortie Count */
            sortie_count: number;
            /**
             * Status
             * @default Черновик
             */
            status: string;
            /** Task Id */
            task_id: string;
            /** Uav Model */
            uav_model: string;
            /** Version */
            version: number;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** SafetyCheckOut */
        SafetyCheckOut: {
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Passed */
            passed: boolean;
            /**
             * Violations
             * @default []
             */
            violations: string[];
        };
        /** SafetyReport */
        SafetyReport: {
            /** Auto Recalc Count */
            auto_recalc_count: number;
            /** Checks */
            checks: components["schemas"]["SafetyCheckOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Plan Id */
            plan_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "Пройдена" | "Есть нарушения";
            /** Task Id */
            task_id: string;
        };
        /** TaskDetail */
        TaskDetail: {
            /** Area */
            area: {
                [key: string]: unknown;
            };
            /** Cloud Cover Pct */
            cloud_cover_pct: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Criterion Alpha */
            criterion_alpha: number;
            /**
             * Criterion Mode
             * @enum {string}
             */
            criterion_mode: "Время" | "Налет" | "Компромисс";
            /** Daylight Warning */
            daylight_warning?: string | null;
            /** Environment Id */
            environment_id: string;
            /** Environment Name */
            environment_name: string;
            /** Gsd Cm */
            gsd_cm: number;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "Черновик" | "Рассчитана" | "Подтверждена";
            /**
             * Survey Type
             * @enum {string}
             */
            survey_type: "RGB" | "мультиспектральная" | "ИК" | "LiDAR" | "геофизическая";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By */
            updated_by?: string | null;
            /** Version */
            version: number;
            /** Wind Speed Ms */
            wind_speed_ms: number | null;
            /** Window End */
            window_end: string | null;
            /** Window Start */
            window_start: string | null;
            /**
             * Work Date
             * Format: date
             */
            work_date: string;
        };
        /** TaskSummary */
        TaskSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Daylight Warning */
            daylight_warning?: string | null;
            /** Environment Id */
            environment_id: string;
            /** Environment Name */
            environment_name: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "Черновик" | "Рассчитана" | "Подтверждена";
            /**
             * Survey Type
             * @enum {string}
             */
            survey_type: "RGB" | "мультиспектральная" | "ИК" | "LiDAR" | "геофизическая";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By */
            updated_by?: string | null;
            /** Version */
            version: number;
            /**
             * Work Date
             * Format: date
             */
            work_date: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Feature Index */
            feature_index: number;
            /**
             * Layer
             * @enum {string}
             */
            layer: "launch_site" | "airspace" | "no_fly" | "obstacle" | "reserve_site";
            /** Message */
            message: string;
            /** Name */
            name?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_environments_api_environments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentSummary"][];
                };
            };
        };
    };
    upload_environment_api_environments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_environment_api_environments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_environment_api_environments__environment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fleet_api_fleet_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetDetail"];
                };
            };
        };
    };
    upload_fleet_api_fleet_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_fleet_api_fleet_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fleet_models_api_fleet_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSpecOut"][];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_plan_jobs_api_plan_jobs_get: {
        parameters: {
            query: {
                task_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_job_api_plan_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_plan_job_api_plan_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_plans_get: {
        parameters: {
            query: {
                task_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_api_plans_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_create_plan_api_plans_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_plan_api_plans__plan_id__confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_plan_api_plans__plan_id__export_get: {
        parameters: {
            query: {
                /** @description формат файла */
                format: "kml" | "geojson";
                /** @description БВС; без него — вся группа */
                uav_id?: string | null;
            };
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_plan_archive_api_plans__plan_id__export_all_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_safety_check_api_safety_checks_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_run_safety_check_api_safety_checks_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_safety_check_api_safety_checks_latest_get: {
        parameters: {
            query: {
                plan_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recheck_safety_check_api_safety_checks_recheck_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_recheck_safety_check_api_safety_checks_recheck_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: {
                environment_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_task_api_tasks_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_tasks__task_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_update_task_api_tasks__task_id__put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
