"""Схема БД и ORM-модели не должны расходиться.

Расхождение проявляется не сразу и не в тестах логики: приложение поднимается,
а падает первый же запрос к колонке, которой нет. Поэтому проверяем явно, что
autogenerate не видит разницы между моделями и накатанными миграциями.
"""

from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected


def test_models_match_migrations(engine, database_url):
    config = Config("alembic.ini")
    config.set_main_option("sqlalchemy.url", database_url)
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:
        raise AssertionError(
            "модели и миграции разошлись — сгенерируйте ревизию "
            f"(alembic revision --autogenerate): {exc}"
        ) from exc
