"""Таблицы предметной области: обстановка, парк БВС, задачи, планы, проверки.

Переносит хранилище из словарей в памяти процесса в PostgreSQL/PostGIS.
Геометрия объектов обстановки и области задачи хранится и как сырой
GeoJSON (то, что отдает API), и как индексируемая geometry-колонка;
маршруты и галсы вылетов — только как geometry: они порождаются нами и
читаются обратно через shapely без потери точности.

Revision ID: 0002
Revises: 0001
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("status IN ('Корректна', 'Содержит ошибки')", name=op.f('ck_environments_status_values')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environments'))
    )
    op.create_index('ix_environments_uploaded_at', 'environments', ['uploaded_at'], unique=False)
    op.create_table('fleet_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('ready_count', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('Корректна', 'Содержит ошибки')", name=op.f('ck_fleet_uploads_status_values')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fleet_uploads'))
    )
    op.create_index('uq_fleet_uploads_is_current', 'fleet_uploads', ['is_current'], unique=True, postgresql_where='is_current')
    op.create_table('environment_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('layer', sa.String(length=32), nullable=False),
    sa.Column('feature_index', sa.Integer(), nullable=False),
    sa.Column('feature', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('buffer_geom', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('h_min_m', sa.Float(), nullable=True),
    sa.Column('h_max_m', sa.Float(), nullable=True),
    sa.Column('safety_buffer_m', sa.Float(), nullable=False),
    sa.CheckConstraint("layer IN ('launch_site', 'airspace', 'no_fly', 'obstacle', 'reserve_site')", name=op.f('ck_environment_features_layer_values')),
    sa.CheckConstraint('h_min_m IS NULL OR h_max_m IS NULL OR h_min_m <= h_max_m', name=op.f('ck_environment_features_height_order')),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_environment_features_environment_id_environments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environment_features')),
    sa.UniqueConstraint('environment_id', 'layer', 'feature_index', name=op.f('uq_environment_features_environment_id_layer_feature_index'))
    )
    op.create_index('ix_environment_features_environment_id_layer', 'environment_features', ['environment_id', 'layer'], unique=False)
    op.create_table('environment_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('layer', sa.String(length=32), nullable=False),
    sa.Column('feature_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_environment_issues_environment_id_environments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environment_issues')),
    sa.UniqueConstraint('environment_id', 'ordinal', name=op.f('uq_environment_issues_environment_id_ordinal'))
    )
    op.create_table('fleet_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('inventory_number', sa.Text(), nullable=False),
    sa.Column('model_key', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('base_launch_site', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['fleet_uploads.id'], name=op.f('fk_fleet_instances_upload_id_fleet_uploads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fleet_instances')),
    sa.UniqueConstraint('upload_id', 'ordinal', name=op.f('uq_fleet_instances_upload_id_ordinal'))
    )
    op.create_index('ix_fleet_instances_eligible', 'fleet_instances', ['upload_id'], unique=False, postgresql_where="is_valid AND status = 'Готов'")
    op.create_table('fleet_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('inventory_number', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['fleet_uploads.id'], name=op.f('fk_fleet_issues_upload_id_fleet_uploads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fleet_issues')),
    sa.UniqueConstraint('upload_id', 'ordinal', name=op.f('uq_fleet_issues_upload_id_ordinal'))
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('survey_type', sa.String(length=32), nullable=False),
    sa.Column('gsd_cm', sa.Float(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('window_start', sa.Time(), nullable=True),
    sa.Column('window_end', sa.Time(), nullable=True),
    sa.Column('wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('criterion_mode', sa.String(length=32), nullable=False),
    sa.Column('criterion_alpha', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('daylight_warning', sa.Text(), nullable=True),
    sa.Column('area', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('area_geom', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('Черновик', 'Рассчитана', 'Подтверждена')", name=op.f('ck_tasks_status_values')),
    sa.CheckConstraint('criterion_alpha BETWEEN 0 AND 1', name=op.f('ck_tasks_alpha_range')),
    sa.CheckConstraint('gsd_cm > 0', name=op.f('ck_tasks_gsd_positive')),
    sa.CheckConstraint('window_start IS NULL OR window_end IS NULL OR window_start <= window_end', name=op.f('ck_tasks_window_order')),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_tasks_environment_id_environments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_environment_id', 'tasks', ['environment_id'], unique=False)
    op.create_index('ix_tasks_updated_at', 'tasks', ['updated_at'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criterion_mode', sa.String(length=32), nullable=False),
    sa.Column('criterion_alpha', sa.Float(), nullable=False),
    sa.Column('j1_s', sa.Float(), nullable=False),
    sa.Column('j2_s', sa.Float(), nullable=False),
    sa.Column('is_optimal', sa.Boolean(), nullable=False),
    sa.Column('uav_model', sa.Text(), nullable=False),
    sa.Column('sortie_count', sa.Integer(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_key', sa.Text(), nullable=False),
    sa.Column('camera_key', sa.Text(), nullable=False),
    sa.Column('height_m', sa.Float(), nullable=False),
    sa.Column('swath_m', sa.Float(), nullable=False),
    sa.Column('cruise_speed_mps', sa.Float(), nullable=False),
    sa.Column('budget_s', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_plans_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('task_id', 'version', name=op.f('uq_plans_task_id_version'))
    )
    op.create_index('ix_plans_task_id_version', 'plans', ['task_id', 'version'], unique=False)
    op.create_table('safety_attempt_counters',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('task_version', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_safety_attempt_counters_attempts_non_negative')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_safety_attempt_counters_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'task_version', name=op.f('pk_safety_attempt_counters'))
    )
    op.create_table('plan_sorties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('uav_id', sa.Text(), nullable=False),
    sa.Column('sortie_index', sa.Integer(), nullable=False),
    sa.Column('takeoff_site', sa.Text(), nullable=True),
    sa.Column('landing_site', sa.Text(), nullable=True),
    sa.Column('start_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('flight_time_s', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('route_geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('survey_tracks_geom', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.CheckConstraint('end_utc >= start_utc', name=op.f('ck_plan_sorties_time_order')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_sorties_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_sorties')),
    sa.UniqueConstraint('plan_id', 'uav_id', 'sortie_index', name=op.f('uq_plan_sorties_plan_id_uav_id_sortie_index'))
    )
    op.create_table('safety_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('requested_plan_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('auto_recalc_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('Пройдена', 'Есть нарушения')", name=op.f('ck_safety_reports_status_values')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_safety_reports_plan_id_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_plan_id'], ['plans.id'], name=op.f('fk_safety_reports_requested_plan_id_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_safety_reports_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safety_reports'))
    )
    op.create_index('ix_safety_reports_plan_id_created_at', 'safety_reports', ['plan_id', 'created_at'], unique=False)
    op.create_index('ix_safety_reports_requested_plan_id_created_at', 'safety_reports', ['requested_plan_id', 'created_at'], unique=False)
    op.create_table('safety_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['safety_reports.id'], name=op.f('fk_safety_checks_report_id_safety_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safety_checks')),
    sa.UniqueConstraint('report_id', 'name', name=op.f('uq_safety_checks_report_id_name')),
    sa.UniqueConstraint('report_id', 'ordinal', name=op.f('uq_safety_checks_report_id_ordinal'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safety_checks')
    op.drop_index('ix_safety_reports_requested_plan_id_created_at', table_name='safety_reports')
    op.drop_index('ix_safety_reports_plan_id_created_at', table_name='safety_reports')
    op.drop_table('safety_reports')
    op.drop_table('plan_sorties')
    op.drop_table('safety_attempt_counters')
    op.drop_index('ix_plans_task_id_version', table_name='plans')
    op.drop_table('plans')
    op.drop_index('ix_tasks_updated_at', table_name='tasks')
    op.drop_index('ix_tasks_environment_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('fleet_issues')
    op.drop_index('ix_fleet_instances_eligible', table_name='fleet_instances', postgresql_where="is_valid AND status = 'Готов'")
    op.drop_table('fleet_instances')
    op.drop_table('environment_issues')
    op.drop_index('ix_environment_features_environment_id_layer', table_name='environment_features')
    op.drop_table('environment_features')
    op.drop_index('uq_fleet_uploads_is_current', table_name='fleet_uploads', postgresql_where='is_current')
    op.drop_table('fleet_uploads')
    op.drop_index('ix_environments_uploaded_at', table_name='environments')
    op.drop_table('environments')
    # ### end Alembic commands ###
