"""Очередь фонового расчета: таблица plan_jobs.

ПЛН.ФТ.3/ФТ.5 — статусы «В очереди / Выполняется / Завершен / Остановлен по
лимиту времени / Ошибка» плюс отмена, стадия и процент прогресса. БЕЗ.ФТ.3 —
счетчик автопересчетов работы и ссылка на итоговый отчет.

Два частичных уникальных индекса задают всю политику дублей: одна активная
работа на задачу (двойной клик по «Рассчитать») и уникальный
Idempotency-Key (ретрай сети).

Revision ID: 0003
Revises: 0002
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=32), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('result_plan_id', sa.UUID(), nullable=True),
    sa.Column('result_report_id', sa.UUID(), nullable=True),
    sa.Column('auto_recalc_count', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('celery_task_id', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('plan', 'safety')", name=op.f('ck_plan_jobs_kind_values')),
    sa.CheckConstraint("status IN ('В очереди', 'Выполняется', 'Завершен', 'Остановлен по лимиту времени', 'Ошибка', 'Отменен')", name=op.f('ck_plan_jobs_status_values')),
    sa.CheckConstraint('progress BETWEEN 0 AND 100', name=op.f('ck_plan_jobs_progress_range')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_jobs_plan_id_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_plan_id'], ['plans.id'], name=op.f('fk_plan_jobs_result_plan_id_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['result_report_id'], ['safety_reports.id'], name=op.f('fk_plan_jobs_result_report_id_safety_reports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_plan_jobs_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_jobs'))
    )
    op.create_index('ix_plan_jobs_task_id_queued_at', 'plan_jobs', ['task_id', 'queued_at'], unique=False)
    op.create_index('uq_plan_jobs_active_task', 'plan_jobs', ['task_id'], unique=True, postgresql_where="status IN ('В очереди', 'Выполняется')")
    op.create_index('uq_plan_jobs_idempotency_key', 'plan_jobs', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_plan_jobs_idempotency_key', table_name='plan_jobs')
    op.drop_index('uq_plan_jobs_active_task', table_name='plan_jobs', postgresql_where="status IN ('В очереди', 'Выполняется')")
    op.drop_index('ix_plan_jobs_task_id_queued_at', table_name='plan_jobs')
    op.drop_table('plan_jobs')
    # ### end Alembic commands ###
