"""Жизненный цикл плана и журнал выгрузок (ЭКС.ФТ.5, ЭКС.ФТ.7).

Статус добавляется существующим планам как «Черновик»: ни один из них еще не
проходил проверку безопасности в терминах нового поля. ``server_default``
нужен только на время наката (колонка NOT NULL на непустой таблице) и сразу
снимается — значение по умолчанию задает приложение, а не БД, иначе
autogenerate будет вечно видеть расхождение с моделью.

CHECK-ограничения дописаны руками: Alembic их для существующей таблицы не
автогенерирует, а без них статус плана перестает быть закрытым перечнем.

Revision ID: 0004
Revises: 0003
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('uav_id', sa.Text(), nullable=True),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.CheckConstraint("format IN ('kml', 'geojson', 'zip')", name=op.f('ck_export_artifacts_format_values')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_export_artifacts_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_artifacts'))
    )
    op.create_index('ix_export_artifacts_plan_id_created_at', 'export_artifacts', ['plan_id', 'created_at'], unique=False)
    op.add_column(
        'plans',
        sa.Column('status', sa.String(length=32), nullable=False, server_default='Черновик'),
    )
    op.alter_column('plans', 'status', server_default=None)
    op.add_column('plans', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('plans', sa.Column('confirmed_by', sa.Text(), nullable=True))
    op.add_column('plans', sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint(
        'ck_plans_status_values',
        'plans',
        "status IN ('Черновик', 'Проверен', 'Подтвержден', 'Выгружен')",
    )
    op.create_check_constraint(
        'ck_plans_confirmed_consistency',
        'plans',
        "(status IN ('Подтвержден', 'Выгружен')) = (confirmed_at IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_plans_confirmed_consistency', 'plans', type_='check')
    op.drop_constraint('ck_plans_status_values', 'plans', type_='check')
    op.drop_column('plans', 'exported_at')
    op.drop_column('plans', 'confirmed_by')
    op.drop_column('plans', 'confirmed_at')
    op.drop_column('plans', 'status')
    op.drop_index('ix_export_artifacts_plan_id_created_at', table_name='export_artifacts')
    op.drop_table('export_artifacts')
    # ### end Alembic commands ###
